# Generated by Django 3.0.9 on 2020-12-22 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticketHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('title', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300)),
                ('status', models.CharField(default='Open', max_length=15)),
                ('priority', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
